#!/bin/bash
echo "$(( 2#$(echo "$WATER" | tr 'water' '01234') + 2#$(echo "$STIR" | tr 'stir' '0123') ))" | awk '{n=$1; b="bestchol"; r=""; while(n){r=substr(b,n%length(b)+1,1) r; n=int(n/length(b))} print r}'
