#!/bin/bash
w=$(echo "$WATER" | tr "water" "01234")
s=$(echo "$STIR" | tr "stir" "0123")
sum=$((5#$w + 4#$s))
base=bestchol
out=""
while [ $sum -gt 0 ]; do
  out="${base:sum%9:1}$out"
  sum=$((sum / 9))
done
echo "$out"
